
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.prefs.Preferences;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Saju
 */
public class JuniperBank extends javax.swing.JFrame {

    /**
     * Creates new form SajuBank
     */
    public JuniperBank() {
        
        
        try {
//             System.out.println("HH");
            Image backgroundImage = ImageIO.read(new File("src/images/hello1.jpg"));
//            System.out.println("Co");
            setContentPane(new JPanel() {
                @Override
                public void paintComponent(Graphics g) {
//                    System.out.println("Comw");
                    g.drawImage(backgroundImage, 0, 0, null);
                }
            });
        } catch (IOException e) {
            e.printStackTrace();
        }
        initComponents();
        
        setTitle("Juniper Bank");
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);
        setResizable(false);
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountButton = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withDrawButton = new javax.swing.JButton();
        extButton = new javax.swing.JButton();
        accountInfoButton = new javax.swing.JButton();
        checkBalanceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createAccountButton.setBackground(new java.awt.Color(102, 0, 102));
        createAccountButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        createAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        depositButton.setBackground(new java.awt.Color(102, 0, 102));
        depositButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        depositButton.setForeground(new java.awt.Color(255, 255, 255));
        depositButton.setText("Deposit");
        depositButton.setPreferredSize(new java.awt.Dimension(90, 25));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withDrawButton.setBackground(new java.awt.Color(102, 0, 102));
        withDrawButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        withDrawButton.setForeground(new java.awt.Color(255, 255, 255));
        withDrawButton.setText("Withdraw");
        withDrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrawButtonActionPerformed(evt);
            }
        });

        extButton.setBackground(new java.awt.Color(102, 0, 102));
        extButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        extButton.setForeground(new java.awt.Color(255, 255, 255));
        extButton.setText("Exit");
        extButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extButtonActionPerformed(evt);
            }
        });

        accountInfoButton.setBackground(new java.awt.Color(102, 0, 102));
        accountInfoButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        accountInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        accountInfoButton.setText("Account Info");
        accountInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountInfoButtonActionPerformed(evt);
            }
        });

        checkBalanceButton.setBackground(new java.awt.Color(102, 0, 102));
        checkBalanceButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        checkBalanceButton.setForeground(new java.awt.Color(255, 255, 255));
        checkBalanceButton.setText("Check Balance");
        checkBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Juniper Bank");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(accountInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(withDrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(extButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withDrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        CreateBankAccount cba = new CreateBankAccount();
        cba.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createAccountButtonActionPerformed

    private void checkBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButtonActionPerformed
        
//        LoginFrame lf = new LoginFrame("CheckBalance");
//        
//        lf.setVisible(true);

//        this.dispose();

    }//GEN-LAST:event_checkBalanceButtonActionPerformed

    private void accountInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountInfoButtonActionPerformed
        
        Preferences prefs = Preferences.userRoot().node("sha/juniper");
//
        String accountNo = prefs.get("accountNo", "unknown");
        String password = prefs.get("password", "unknown");
        
        if (accountNo.equals("unknown") || password.equals("unknown")) {
            LoginFrame lf = new LoginFrame("AccountInfo");
            lf.setVisible(true);
        } else {
            AccountInfoFrame aif = new AccountInfoFrame();
            aif.setVisible(true);
        }
        

    }//GEN-LAST:event_accountInfoButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        Preferences prefs = Preferences.userRoot().node("sha/juniper");
//
        String accountNo = prefs.get("accountNo", "unknown");
        String password = prefs.get("password", "unknown");
        
        if (accountNo.equals("unknown") || password.equals("unknown")) {
            LoginFrame lf = new LoginFrame("Deposit");
            lf.setVisible(true);
        } else {
            DepositFrame aif = new DepositFrame(accountNo, password);
            aif.setVisible(true);
        }
        
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withDrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrawButtonActionPerformed
        Preferences prefs = Preferences.userRoot().node("sha/juniper");
//
        String accountNo = prefs.get("accountNo", "unknown");
        String password = prefs.get("password", "unknown");
        
//        if (accountNo.equals("unknown") || password.equals("unknown")) {
//            LoginFrame lf = new LoginFrame("Withdraw");
//            lf.setVisible(true);
//        } else {
//            WithdrawFrame aif = new WithdrawFrame();
//            aif.setVisible(true);
//        }
        
    }//GEN-LAST:event_withDrawButtonActionPerformed

    private void extButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extButtonActionPerformed

        
        dispose();
        setVisible(false);
    }//GEN-LAST:event_extButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuniperBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuniperBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuniperBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuniperBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JuniperBank sb = new JuniperBank();
                sb.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountInfoButton;
    private javax.swing.JButton checkBalanceButton;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton extButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton withDrawButton;
    // End of variables declaration//GEN-END:variables
}
